test:
  - NSE:ETERNAL-EQ

nifty50:
  - NSE:ADANIENT-EQ
  - NSE:ADANIPORTS-EQ
  - NSE:APOLLOHOSP-EQ
  - NSE:ASIANPAINT-EQ
  - NSE:AXISBANK-EQ
  - NSE:BAJAJ-AUTO-EQ
  - NSE:BAJAJFINSV-EQ
  - NSE:BAJFINANCE-EQ
  - NSE:BEL-EQ
  - NSE:BHARTIARTL-EQ
  - NSE:CIPLA-EQ
  - NSE:COALINDIA-EQ
  - NSE:DRREDDY-EQ
  - NSE:EICHERMOT-EQ
  - NSE:ETERNAL-EQ
  - NSE:GRASIM-EQ
  - NSE:HCLTECH-EQ
  - NSE:HDFCBANK-EQ
  - NSE:HDFCLIFE-EQ
  - NSE:HINDALCO-EQ
  - NSE:HINDUNILVR-EQ
  - NSE:ICICIBANK-EQ
  - NSE:INDIGO-EQ
  - NSE:INFY-EQ
  - NSE:ITC-EQ
  - NSE:JIOFIN-EQ
  - NSE:JSWSTEEL-EQ
  - NSE:KOTAKBANK-EQ
  - NSE:LT-EQ
  - NSE:M&M-EQ
  - NSE:MARUTI-EQ
  - NSE:MAXHEALTH-EQ
  - NSE:NESTLEIND-EQ
  - NSE:NTPC-EQ
  - NSE:ONGC-EQ
  - NSE:POWERGRID-EQ
  - NSE:RELIANCE-EQ
  - NSE:SBILIFE-EQ
  - NSE:SBIN-EQ
  - NSE:SHRIRAMFIN-EQ
  - NSE:SUNPHARMA-EQ
  - NSE:TATACONSUM-EQ
  - NSE:TATASTEEL-EQ
  - NSE:TCS-EQ
  - NSE:TECHM-EQ
  - NSE:TITAN-EQ
  - NSE:TMPV-EQ
  - NSE:TRENT-EQ
  - NSE:ULTRACEMCO-EQ
  - NSE:WIPRO-EQ

indices:
  - "NSE:NIFTY50-INDEX"
  - "NSE:NIFTYBANK-INDEX"

nifty100:
  - NSE:ABB-EQ
  - NSE:ADANIENSOL-EQ
  - NSE:ADANIENT-EQ
  - NSE:ADANIGREEN-EQ
  - NSE:ADANIPORTS-EQ
  - NSE:ADANIPOWER-EQ
  - NSE:AMBUJACEM-EQ
  - NSE:APOLLOHOSP-EQ
  - NSE:ASIANPAINT-EQ
  - NSE:AXISBANK-EQ
  - NSE:BAJAJ-AUTO-EQ
  - NSE:BAJAJFINSV-EQ
  - NSE:BAJAJHLDNG-EQ
  - NSE:BAJFINANCE-EQ
  - NSE:BANKBARODA-EQ
  - NSE:BEL-EQ
  - NSE:BHEL-EQ
  - NSE:BHARTIARTL-EQ
  - NSE:BOSCHLTD-EQ
  - NSE:BPCL-EQ
  - NSE:BRITANNIA-EQ
  - NSE:CANBK-EQ
  - NSE:CGPOWER-EQ
  - NSE:CHOLAFIN-EQ
  - NSE:CIPLA-EQ
  - NSE:COALINDIA-EQ
  - NSE:DABUR-EQ
  - NSE:DIVISLAB-EQ
  - NSE:DLF-EQ
  - NSE:DMART-EQ
  - NSE:DRREDDY-EQ
  - NSE:EICHERMOT-EQ
  - NSE:ETERNAL-EQ
  - NSE:GAIL-EQ
  - NSE:GODREJCP-EQ
  - NSE:GRASIM-EQ
  - NSE:HAL-EQ
  - NSE:HAVELLS-EQ
  - NSE:HCLTECH-EQ
  - NSE:HDFCBANK-EQ
  - NSE:HDFCLIFE-EQ
  - NSE:HINDALCO-EQ
  - NSE:HINDUNILVR-EQ
  - NSE:HINDZINC-EQ
  - NSE:HYUNDAI-EQ
  - NSE:ICICIBANK-EQ
  - NSE:ICICIGI-EQ
  - NSE:INDHOTEL-EQ
  - NSE:INDIGO-EQ
  - NSE:INFY-EQ
  - NSE:IOC-EQ
  - NSE:IRCTC-EQ
  - NSE:IRFC-EQ
  - NSE:ITC-EQ
  - NSE:JINDALSTEL-EQ
  - NSE:JIOFIN-EQ
  - NSE:JSWENERGY-EQ
  - NSE:JSWSTEEL-EQ
  - NSE:KOTAKBANK-EQ
  - NSE:LICI-EQ
  - NSE:LODHA-EQ
  - NSE:LT-EQ
  - NSE:M&M-EQ
  - NSE:MARUTI-EQ
  - NSE:MAXHEALTH-EQ
  - NSE:MAZDOCK-EQ
  - NSE:MOTHERSON-EQ
  - NSE:NAUKRI-EQ
  - NSE:NESTLEIND-EQ
  - NSE:NHPC-EQ
  - NSE:NTPC-EQ
  - NSE:ONGC-EQ
  - NSE:PFC-EQ
  - NSE:PIDILITIND-EQ
  - NSE:PNB-EQ
  - NSE:POWERGRID-EQ
  - NSE:RECLTD-EQ
  - NSE:RELIANCE-EQ
  - NSE:SBILIFE-EQ
  - NSE:SBIN-EQ
  - NSE:SHREECEM-EQ
  - NSE:SHRIRAMFIN-EQ
  - NSE:SIEMENS-EQ
  - NSE:SUNPHARMA-EQ
  - NSE:TATACONSUM-EQ
  - NSE:TATAPOWER-EQ
  - NSE:TATASTEEL-EQ
  - NSE:TCS-EQ
  - NSE:TECHM-EQ
  - NSE:TITAN-EQ
  - NSE:TMPV-EQ
  - NSE:TORNTPHARM-EQ
  - NSE:TRENT-EQ
  - NSE:TVSMOTOR-EQ
  - NSE:ULTRACEMCO-EQ
  - NSE:VBL-EQ
  - NSE:VEDL-EQ
  - NSE:WIPRO-EQ
  - NSE:ZYDUSLIFE-EQ

nifty200:
  - NSE:ABB-EQ
  - NSE:ABCAPITAL-EQ
  - NSE:ACC-EQ
  - NSE:ADANIENSOL-EQ
  - NSE:ADANIENT-EQ
  - NSE:ADANIGREEN-EQ
  - NSE:ADANIPORTS-EQ
  - NSE:ADANIPOWER-EQ
  - NSE:ALKEM-EQ
  - NSE:AMBUJACEM-EQ
  - NSE:APOLLOHOSP-EQ
  - NSE:APOLLOTYRE-EQ
  - NSE:ASHOKLEY-EQ
  - NSE:ASIANPAINT-EQ
  - NSE:ASTRAL-EQ
  - NSE:ATGL-EQ
  - NSE:AUBANK-EQ
  - NSE:AUROPHARMA-EQ
  - NSE:AXISBANK-EQ
  - NSE:BAJAJ-AUTO-EQ
  - NSE:BAJAJFINSV-EQ
  - NSE:BAJAJHLDNG-EQ
  - NSE:BAJFINANCE-EQ
  - NSE:BALKRISIND-EQ
  - NSE:BANDHANBNK-EQ
  - NSE:BANKBARODA-EQ
  - NSE:BANKINDIA-EQ
  - NSE:BEL-EQ
  - NSE:BERGEPAINT-EQ
  - NSE:BHARATFORG-EQ
  - NSE:BHARTIARTL-EQ
  - NSE:BHEL-EQ
  - NSE:BIOCON-EQ
  - NSE:BOSCHLTD-EQ
  - NSE:BPCL-EQ
  - NSE:BRITANNIA-EQ
  - NSE:BSE-EQ
  - NSE:CANBK-EQ
  - NSE:CGPOWER-EQ
  - NSE:CHOLAFIN-EQ
  - NSE:CIPLA-EQ
  - NSE:COALINDIA-EQ
  - NSE:COFORGE-EQ
  - NSE:COLPAL-EQ
  - NSE:CONCOR-EQ
  - NSE:CROMPTON-EQ
  - NSE:CUMMINSIND-EQ
  - NSE:DABUR-EQ
  - NSE:DALBHARAT-EQ
  - NSE:DEEPAKNTR-EQ
  - NSE:DIVISLAB-EQ
  - NSE:DIXON-EQ
  - NSE:DLF-EQ
  - NSE:DMART-EQ
  - NSE:DRREDDY-EQ
  - NSE:EICHERMOT-EQ
  - NSE:ESCORTS-EQ
  - NSE:ETERNAL-EQ
  - NSE:EXIDEIND-EQ
  - NSE:FEDERALBNK-EQ
  - NSE:FORTIS-EQ
  - NSE:GAIL-EQ
  - NSE:GLAND-EQ
  - NSE:GLENMARK-EQ
  - NSE:GMRAIRPORT-EQ
  - NSE:GODREJCP-EQ
  - NSE:GODREJPROP-EQ
  - NSE:GRASIM-EQ
  - NSE:GUJGASLTD-EQ
  - NSE:HAL-EQ
  - NSE:HAVELLS-EQ
  - NSE:HCLTECH-EQ
  - NSE:HDFCAMC-EQ
  - NSE:HDFCBANK-EQ
  - NSE:HDFCLIFE-EQ
  - NSE:HEROMOTOCO-EQ
  - NSE:HINDALCO-EQ
  - NSE:HINDPETRO-EQ
  - NSE:HINDUNILVR-EQ
  - NSE:HINDZINC-EQ
  - NSE:ICICIBANK-EQ
  - NSE:ICICIGI-EQ
  - NSE:ICICIPRULI-EQ
  - NSE:IDEA-EQ
  - NSE:IDFCFIRSTB-EQ
  - NSE:IEX-EQ
  - NSE:IGL-EQ
  - NSE:INDHOTEL-EQ
  - NSE:INDIANB-EQ
  - NSE:INDIGO-EQ
  - NSE:INDUSINDBK-EQ
  - NSE:INDUSTOWER-EQ
  - NSE:INFY-EQ
  - NSE:IOC-EQ
  - NSE:IRCTC-EQ
  - NSE:IRFC-EQ
  - NSE:ITC-EQ
  - NSE:JINDALSTEL-EQ
  - NSE:JIOFIN-EQ
  - NSE:JKCEMENT-EQ
  - NSE:JSWENERGY-EQ
  - NSE:JSWSTEEL-EQ
  - NSE:JUBLFOOD-EQ
  - NSE:KOTAKBANK-EQ
  - NSE:LALPATHLAB-EQ
  - NSE:LAURUSLABS-EQ
  - NSE:LICHSGFIN-EQ
  - NSE:LICI-EQ
  - NSE:LODHA-EQ
  - NSE:LT-EQ
  - NSE:LTIM-EQ
  - NSE:LTTS-EQ
  - NSE:LUPIN-EQ
  - NSE:M&M-EQ
  - NSE:M&MFIN-EQ
  - NSE:MANAPPURAM-EQ
  - NSE:MANKIND-EQ
  - NSE:MARICO-EQ
  - NSE:MARUTI-EQ
  - NSE:MAXHEALTH-EQ
  - NSE:MAZDOCK-EQ
  - NSE:MCX-EQ
  - NSE:METROPOLIS-EQ
  - NSE:MFSL-EQ
  - NSE:MGL-EQ
  - NSE:MOTHERSON-EQ
  - NSE:MPHASIS-EQ
  - NSE:MRF-EQ
  - NSE:MUTHOOTFIN-EQ
  - NSE:NAM-INDIA-EQ
  - NSE:NATIONALUM-EQ
  - NSE:NAUKRI-EQ
  - NSE:NAVINFLUOR-EQ
  - NSE:NESTLEIND-EQ
  - NSE:NHPC-EQ
  - NSE:NMDC-EQ
  - NSE:NTPC-EQ
  - NSE:NYKAA-EQ
  - NSE:OBEROIRLTY-EQ
  - NSE:OFSS-EQ
  - NSE:OIL-EQ
  - NSE:ONGC-EQ
  - NSE:PAGEIND-EQ
  - NSE:PERSISTENT-EQ
  - NSE:PETRONET-EQ
  - NSE:PFC-EQ
  - NSE:PFIZER-EQ
  - NSE:PIDILITIND-EQ
  - NSE:PIIND-EQ
  - NSE:PNB-EQ
  - NSE:POLICYBZR-EQ
  - NSE:POLYCAB-EQ
  - NSE:POWERGRID-EQ
  - NSE:PRESTIGE-EQ
  - NSE:PVRINOX-EQ
  - NSE:RAMCOCEM-EQ
  - NSE:RBLBANK-EQ
  - NSE:RECLTD-EQ
  - NSE:RELIANCE-EQ
  - NSE:SAIL-EQ
  - NSE:SBICARD-EQ
  - NSE:SBILIFE-EQ
  - NSE:SBIN-EQ
  - NSE:SHREECEM-EQ
  - NSE:SHRIRAMFIN-EQ
  - NSE:SIEMENS-EQ
  - NSE:SOLARINDS-EQ
  - NSE:SRF-EQ
  - NSE:SUNPHARMA-EQ
  - NSE:SUNTV-EQ
  - NSE:SUPREMEIND-EQ
  - NSE:SUZLON-EQ
  - NSE:SYNGENE-EQ
  - NSE:TATACHEM-EQ
  - NSE:TATACOMM-EQ
  - NSE:TATACONSUM-EQ
  - NSE:TATAELXSI-EQ
  - NSE:TATAPOWER-EQ
  - NSE:TATASTEEL-EQ
  - NSE:TCS-EQ
  - NSE:TECHM-EQ
  - NSE:TITAN-EQ
  - NSE:TMPV-EQ
  - NSE:TORNTPHARM-EQ
  - NSE:TORNTPOWER-EQ
  - NSE:TRENT-EQ
  - NSE:TVSMOTOR-EQ
  - NSE:UBL-EQ
  - NSE:ULTRACEMCO-EQ
  - NSE:UNIONBANK-EQ
  - NSE:UNITDSPR-EQ
  - NSE:UPL-EQ
  - NSE:VBL-EQ
  - NSE:VEDL-EQ
  - NSE:VOLTAS-EQ
  - NSE:WHIRLPOOL-EQ
  - NSE:WIPRO-EQ
  - NSE:ZYDUSLIFE-EQ

bank:
  - NSE:AUBANK-EQ
  - NSE:AXISBANK-EQ
  - NSE:BANKBARODA-EQ
  - NSE:CANBK-EQ
  - NSE:FEDERALBNK-EQ
  - NSE:HDFCBANK-EQ
  - NSE:ICICIBANK-EQ
  - NSE:IDFCFIRSTB-EQ
  - NSE:INDUSINDBK-EQ
  - NSE:KOTAKBANK-EQ
  - NSE:PNB-EQ
  - NSE:SBIN-EQ
  - NSE:UNIONBANK-EQ
  - NSE:YESBANK-EQ

auto: 
  - NSE:ASHOKLEY-EQ
  - NSE:BAJAJ-AUTO-EQ
  - NSE:BOSCHLTD-EQ
  - NSE:EICHERMOT-EQ
  - NSE:HEROMOTOCO-EQ
  - NSE:M&M-EQ
  - NSE:MARUTI-EQ
  - NSE:TMCV-EQ
  - NSE:TMPV-EQ
  - NSE:TVSMOTOR-EQ

fmcg:
  - NSE:BRITANNIA-EQ
  - NSE:COLPAL-EQ
  - NSE:DABUR-EQ
  - NSE:GODREJCP-EQ
  - NSE:HINDUNILVR-EQ
  - NSE:ITC-EQ
  - NSE:MARICO-EQ
  - NSE:NESTLEIND-EQ
  - NSE:PATANJALI-EQ
  - NSE:TATACONSUM-EQ
  - NSE:UNITDSPR-EQ
  - NSE:VBL-EQ

it:
  - NSE:COFORGE-EQ
  - NSE:HCLTECH-EQ
  - NSE:INFY-EQ
  - NSE:LTIM-EQ
  - NSE:MPHASIS-EQ
  - NSE:OFSS-EQ
  - NSE:PERSISTENT-EQ
  - NSE:TCS-EQ
  - NSE:TECHM-EQ
  - NSE:WIPRO-EQ

metals:
  - NSE:COALINDIA-EQ
  - NSE:HINDALCO-EQ
  - NSE:JINDALSTEL-EQ
  - NSE:JSWSTEEL-EQ
  - NSE:NATIONALUM-EQ
  - NSE:NMDC-EQ
  - NSE:SAIL-EQ
  - NSE:TATASTEEL-EQ
  - NSE:VEDL-EQ

pharma:
  - NSE:APOLLOHOSP-EQ
  - NSE:AUROPHARMA-EQ
  - NSE:BIOCON-EQ
  - NSE:CIPLA-EQ
  - NSE:DIVISLAB-EQ
  - NSE:DRREDDY-EQ
  - NSE:GLENMARK-EQ
  - NSE:LUPIN-EQ
  - NSE:MAXHEALTH-EQ
  - NSE:SUNPHARMA-EQ
  - NSE:ZYDUSLIFE-EQ